/* Generated By:JavaCC: Do not edit this line. PHPParserConstants.java */
package gatchan.phpparser.parser;

public interface PHPParserConstants {

  int EOF = 0;
  int PHPSTARTSHORT = 1;
  int PHPSTARTLONG = 2;
  int PHPECHOSTART = 3;
  int PHPEND = 4;
  int SINGLE_LINE_COMMENT = 21;
  int PUBLIC = 26;
  int PROTECTED = 27;
  int PRIVATE = 28;
  int ABSTRACT = 29;
  int INTERFACE = 30;
  int IMPLEMENTS = 31;
  int FINAL = 32;
  int TRY = 33;
  int CATCH = 34;
  int THROW = 35;
  int CLASS = 36;
  int FUNCTION = 37;
  int VAR = 38;
  int IF = 39;
  int ELSEIF = 40;
  int ELSE = 41;
  int ARRAY = 42;
  int BREAK = 43;
  int LIST = 44;
  int PRINT = 45;
  int ECHO = 46;
  int INCLUDE = 47;
  int REQUIRE = 48;
  int INCLUDE_ONCE = 49;
  int REQUIRE_ONCE = 50;
  int GLOBAL = 51;
  int STATIC = 52;
  int CASE = 53;
  int CONST = 54;
  int CONTINUE = 55;
  int _DEFAULT = 56;
  int DO = 57;
  int EXTENDS = 58;
  int FOR = 59;
  int NEW = 60;
  int CLONE = 61;
  int RETURN = 62;
  int SWITCH = 63;
  int WHILE = 64;
  int ENDWHILE = 65;
  int ENDSWITCH = 66;
  int ENDIF = 67;
  int ENDFOR = 68;
  int ENDFOREACH = 69;
  int FOREACH = 70;
  int AS = 71;
  int CLASSACCESS = 72;
  int STATICCLASSACCESS = 73;
  int ARRAYASSIGN = 74;
  int DEFINE = 75;
  int GOTO = 76;
  int NULL = 77;
  int SUPER = 78;
  int THIS = 79;
  int TRUE = 80;
  int FALSE = 81;
  int INSTANCEOF = 82;
  int STRING = 83;
  int OBJECT = 84;
  int BOOL = 85;
  int BOOLEAN = 86;
  int REAL = 87;
  int DOUBLE = 88;
  int FLOAT = 89;
  int INT = 90;
  int INTEGER = 91;
  int AT = 92;
  int BANG = 93;
  int TILDE = 94;
  int HOOK = 95;
  int COLON = 96;
  int OR_OR = 97;
  int AND_AND = 98;
  int PLUS_PLUS = 99;
  int MINUS_MINUS = 100;
  int PLUS = 101;
  int MINUS = 102;
  int STAR = 103;
  int SLASH = 104;
  int BIT_AND = 105;
  int BIT_OR = 106;
  int BIT_XOR = 107;
  int REMAINDER = 108;
  int LSHIFT = 109;
  int RSIGNEDSHIFT = 110;
  int RUNSIGNEDSHIFT = 111;
  int _ORL = 112;
  int XOR = 113;
  int _ANDL = 114;
  int INTEGER_LITERAL = 115;
  int DECIMAL_LITERAL = 116;
  int HEX_LITERAL = 117;
  int OCTAL_LITERAL = 118;
  int FLOATING_POINT_LITERAL = 119;
  int EXPONENT = 120;
  int STRING_LITERAL = 121;
  int STRING_2 = 122;
  int STRING_3 = 123;
  int ESCAPED = 124;
  int DOUBLEQUOTE = 125;
  int DOLLARS = 126;
  int DOUBLEQUOTE2 = 127;
  int LBRACE1 = 128;
  int RBRACE1 = 132;
  int ID = 133;
  int HEREDOCSTARTTOKEN = 136;
  int DOLLAR = 137;
  int IDENTIFIER = 138;
  int LETTER = 139;
  int DIGIT = 140;
  int SPECIAL = 141;
  int LPAREN = 143;
  int RPAREN = 144;
  int LBRACE = 145;
  int RBRACE = 146;
  int LBRACKET = 147;
  int RBRACKET = 148;
  int SEMICOLON = 149;
  int COMMA = 150;
  int DOT = 151;
  int GT = 152;
  int LT = 153;
  int EQUAL_EQUAL = 154;
  int LE = 155;
  int GE = 156;
  int NOT_EQUAL = 157;
  int DIF = 158;
  int BANGDOUBLEEQUAL = 159;
  int TRIPLEEQUAL = 160;
  int ASSIGN = 161;
  int PLUSASSIGN = 162;
  int MINUSASSIGN = 163;
  int STARASSIGN = 164;
  int SLASHASSIGN = 165;
  int ANDASSIGN = 166;
  int ORASSIGN = 167;
  int XORASSIGN = 168;
  int DOTASSIGN = 169;
  int REMASSIGN = 170;
  int TILDEEQUAL = 171;
  int LSHIFTASSIGN = 172;
  int RSIGNEDSHIFTASSIGN = 173;

  int DEFAULT = 0;
  int PHPPARSING = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int IN_VARIABLE = 3;
  int IN_FORMAL_COMMENT = 4;
  int IN_MULTI_LINE_COMMENT = 5;
  int IN_STRING = 6;
  int DOLLAR_IN_STRING = 7;
  int SKIPSTRING = 8;
  int DOLLAR_IN_STRING_EXPR = 9;

  String[] tokenImage = {
    "<EOF>",
    "\"<?\"",
    "\"<?php\"",
    "\"<?=\"",
    "\"?>\"",
    "<token of kind 5>",
    "\"<?xml\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 19>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 22>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 25>",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"abstract\"",
    "\"interface\"",
    "\"implements\"",
    "\"final\"",
    "\"try\"",
    "\"catch\"",
    "\"throw\"",
    "\"class\"",
    "\"function\"",
    "\"var\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"array\"",
    "\"break\"",
    "\"list\"",
    "\"print\"",
    "\"echo\"",
    "\"include\"",
    "\"require\"",
    "\"include_once\"",
    "\"require_once\"",
    "\"global\"",
    "\"static\"",
    "\"case\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"extends\"",
    "\"for\"",
    "\"new\"",
    "\"clone\"",
    "\"return\"",
    "\"switch\"",
    "\"while\"",
    "\"endwhile\"",
    "\"endswitch\"",
    "\"endif\"",
    "\"endfor\"",
    "\"endforeach\"",
    "\"foreach\"",
    "\"as\"",
    "\"->\"",
    "\"::\"",
    "\"=>\"",
    "\"define\"",
    "\"goto\"",
    "\"null\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"instanceof\"",
    "\"string\"",
    "\"object\"",
    "\"bool\"",
    "\"boolean\"",
    "\"real\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"integer\"",
    "\"@\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"OR\"",
    "\"XOR\"",
    "\"AND\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<STRING_2>",
    "<STRING_3>",
    "<ESCAPED>",
    "\"\\\"\"",
    "\"$\"",
    "\"\\\"\"",
    "\"{\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 131>",
    "\"}\"",
    "<ID>",
    "<token of kind 134>",
    "<token of kind 135>",
    "\"<<<\"",
    "\"$\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL>",
    "<token of kind 142>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"!==\"",
    "\"===\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\".=\"",
    "\"%=\"",
    "\"~=\"",
    "\"<<=\"",
    "\">>=\"",
  };

}
